version: "3"

services:
  web:
    ports:
      - "1727:80"
    restart: always
    build:
      context: .
      dockerfile: BattleArena/Dockerfile

networks:
  default:
    external: 
      name: orchestr